(module
  (type $FUNCSIG$vii (func (param i32 i32)))
  (import "test" "equals" (func $equals (param i32 i32)))
  (table 0 anyfunc)
  (memory $0 1)
  (export "memory" (memory $0))
  (export "init" (func $init))
  (export "main" (func $main))
  (func $init (result i32)
    (i32.const 0)
  )
  (func $main (result i32)
    (call $equals
      (i32.const 0)
      (i32.const 0)
    )
    (i32.const 0)
  )
)
